
# Set up the BIDS output path - it is referenced from the home directory of your PC
# For example, if your home directory is /home/username and you have a data/bids directory where you have the BIDS data
# then the BIDS_ROOT path will be 'data/bids/'
BIDS_ROOT: './data/bids/'

# This is the actual path to the directory containing xdf files
PROJECT_ROOT : './data/projects/'

# This is the actual path to the directory containing the stimulus files
PROJECTS_STIM_ROOT : './data/project_stimulus/'